import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  return worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );
}

test("server-renders the Shifahiya course with lesson eighty", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  assert.match(response.headers.get("content-type") ?? "", /^text\/html\b/i);

  const html = await response.text();
  assert.match(html, /<title>Аш-Шифахия — арабский шаг за шагом<\/title>/i);
  assert.match(html, /80 из 100 уроков готовы/);
  assert.match(html, /Известный правитель и занятый министр/);
  assert.match(html, /الدَّرْسُ الخَامِسُ عَشَرَ/);
  assert.match(html, /48 заданий/);
  assert.doesNotMatch(html, /Your site is taking shape|Building your site/);
});

test("keeps lesson fifteen data and local progress support in the app", async () => {
  const page = await readFile(new URL("../app/page.tsx", import.meta.url), "utf8");
  const lessonFifteen = await readFile(new URL("../content/lesson-15.ts", import.meta.url), "utf8");
  const catalog = await readFile(new URL("../content/index.ts", import.meta.url), "utf8");
  const contentFiles = await readdir(new URL("../content/", import.meta.url));

  const lessonSixteen = await readFile(new URL("../content/lesson-16.ts", import.meta.url), "utf8");
  const lessonSeventeen = await readFile(new URL("../content/lesson-17.ts", import.meta.url), "utf8");
  const lessonEighteen = await readFile(new URL("../content/lesson-18.ts", import.meta.url), "utf8");
  const lessonNineteen = await readFile(new URL("../content/lesson-19.ts", import.meta.url), "utf8");
  const lessonTwenty = await readFile(new URL("../content/lesson-20.ts", import.meta.url), "utf8");
  const lessonTwentyOne = await readFile(new URL("../content/lesson-21.ts", import.meta.url), "utf8");
  const lessonTwentyTwo = await readFile(new URL("../content/lesson-22.ts", import.meta.url), "utf8");
  const lessonTwentyThree = await readFile(new URL("../content/lesson-23.ts", import.meta.url), "utf8");
  const lessonTwentyFour = await readFile(new URL("../content/lesson-24.ts", import.meta.url), "utf8");
  const lessonTwentyFive = await readFile(new URL("../content/lesson-25.ts", import.meta.url), "utf8");
  const lessonTwentySix = await readFile(new URL("../content/lesson-26.ts", import.meta.url), "utf8");
  const lessonTwentySeven = await readFile(new URL("../content/lesson-27.ts", import.meta.url), "utf8");
  const lessonTwentyEight = await readFile(new URL("../content/lesson-28.ts", import.meta.url), "utf8");
  const lessonTwentyNine = await readFile(new URL("../content/lesson-29.ts", import.meta.url), "utf8");
  const lessonThirty = await readFile(new URL("../content/lesson-30.ts", import.meta.url), "utf8");
  const lessonThirtyOne = await readFile(new URL("../content/lesson-31.ts", import.meta.url), "utf8");
  const lessonThirtyTwo = await readFile(new URL("../content/lesson-32.ts", import.meta.url), "utf8");
  const lessonThirtyThree = await readFile(new URL("../content/lesson-33.ts", import.meta.url), "utf8");
  const lessonThirtyFour = await readFile(new URL("../content/lesson-34.ts", import.meta.url), "utf8");
  const lessonThirtyFive = await readFile(new URL("../content/lesson-35.ts", import.meta.url), "utf8");
  const lessonThirtySix = await readFile(new URL("../content/lesson-36.ts", import.meta.url), "utf8");
  const lessonThirtySeven = await readFile(new URL("../content/lesson-37.ts", import.meta.url), "utf8");
  const lessonThirtyEight = await readFile(new URL("../content/lesson-38.ts", import.meta.url), "utf8");
  const lessonThirtyNine = await readFile(new URL("../content/lesson-39.ts", import.meta.url), "utf8");
  const lessonForty = await readFile(new URL("../content/lesson-40.ts", import.meta.url), "utf8");
  const lessonFortyOne = await readFile(new URL("../content/lesson-41.ts", import.meta.url), "utf8");
  const lessonFortyTwo = await readFile(new URL("../content/lesson-42.ts", import.meta.url), "utf8");
  const lessonFortyThree = await readFile(new URL("../content/lesson-43.ts", import.meta.url), "utf8");
  const lessonFortyFour = await readFile(new URL("../content/lesson-44.ts", import.meta.url), "utf8");
  const lessonFortyFive = await readFile(new URL("../content/lesson-45.ts", import.meta.url), "utf8");
  const lessonFortySix = await readFile(new URL("../content/lesson-46.ts", import.meta.url), "utf8");
  const lessonFortySeven = await readFile(new URL("../content/lesson-47.ts", import.meta.url), "utf8");
  const lessonFortyEight = await readFile(new URL("../content/lesson-48.ts", import.meta.url), "utf8");
  const lessonFortyNine = await readFile(new URL("../content/lesson-49.ts", import.meta.url), "utf8");
  const lessonFifty = await readFile(new URL("../content/lesson-50.ts", import.meta.url), "utf8");
  const lessonFiftyOne = await readFile(new URL("../content/lesson-51.ts", import.meta.url), "utf8");
  const lessonFiftyTwo = await readFile(new URL("../content/lesson-52.ts", import.meta.url), "utf8");
  const lessonFiftyThree = await readFile(new URL("../content/lesson-53.ts", import.meta.url), "utf8");
  const lessonFiftyFour = await readFile(new URL("../content/lesson-54.ts", import.meta.url), "utf8");
  const lessonFiftyFive = await readFile(new URL("../content/lesson-55.ts", import.meta.url), "utf8");
  const lessonFiftySix = await readFile(new URL("../content/lesson-56.ts", import.meta.url), "utf8");
  const lessonFiftySeven = await readFile(new URL("../content/lesson-57.ts", import.meta.url), "utf8");
  const lessonFiftyEight = await readFile(new URL("../content/lesson-58.ts", import.meta.url), "utf8");
  const lessonFiftyNine = await readFile(new URL("../content/lesson-59.ts", import.meta.url), "utf8");
  const lessonSixty = await readFile(new URL("../content/lesson-60.ts", import.meta.url), "utf8");
  const lessonSixtyOne = await readFile(new URL("../content/lesson-61.ts", import.meta.url), "utf8");
  const lessonSixtyTwo = await readFile(new URL("../content/lesson-62.ts", import.meta.url), "utf8");
  const lessonSixtyThree = await readFile(new URL("../content/lesson-63.ts", import.meta.url), "utf8");
  const lessonSixtyFour = await readFile(new URL("../content/lesson-64.ts", import.meta.url), "utf8");
  const lessonSixtyFive = await readFile(new URL("../content/lesson-65.ts", import.meta.url), "utf8");
  const lessonSixtySix = await readFile(new URL("../content/lesson-66.ts", import.meta.url), "utf8");
  const lessonSixtySeven = await readFile(new URL("../content/lesson-67.ts", import.meta.url), "utf8");
  const lessonSixtyEight = await readFile(new URL("../content/lesson-68.ts", import.meta.url), "utf8");
  const lessonSixtyNine = await readFile(new URL("../content/lesson-69.ts", import.meta.url), "utf8");
  const lessonSeventy = await readFile(new URL("../content/lesson-70.ts", import.meta.url), "utf8");
  const lessonSeventyOne = await readFile(new URL("../content/lesson-71.ts", import.meta.url), "utf8");
  const lessonSeventyTwo = await readFile(new URL("../content/lesson-72.ts", import.meta.url), "utf8");
  const lessonSeventyThree = await readFile(new URL("../content/lesson-73.ts", import.meta.url), "utf8");
  const lessonSeventyFour = await readFile(new URL("../content/lesson-74.ts", import.meta.url), "utf8");
  const lessonSeventyFive = await readFile(new URL("../content/lesson-75.ts", import.meta.url), "utf8");
  const lessonSeventySix = await readFile(new URL("../content/lesson-76.ts", import.meta.url), "utf8");
  const lessonSeventySeven = await readFile(new URL("../content/lesson-77.ts", import.meta.url), "utf8");
  const lessonSeventyEight = await readFile(new URL("../content/lesson-78.ts", import.meta.url), "utf8");
  const lessonSeventyNine = await readFile(new URL("../content/lesson-79.ts", import.meta.url), "utf8");
  const lessonEighty = await readFile(new URL("../content/lesson-80.ts", import.meta.url), "utf8");
  assert.equal(contentFiles.filter((file) => /^lesson-\d{2}\.ts$/.test(file)).length, 80);
  assert.match(lessonFifteen, /export const lessonFifteen: Lesson/);
  assert.match(lessonFifteen, /مَلِكٌ/);
  assert.match(lessonFifteen, /مُتَأَهِّلَاتٌ/);
  assert.match(lessonFifteen, /أَمَّا \.\.\. فَـ \.\.\./);
  assert.match(catalog, /export const rawLessons/);
  assert.match(lessonSixteen, /export const lessonSixteen: Lesson/);
  assert.match(lessonSixteen, /بِلَادٌ/);
  assert.match(lessonSixteen, /هَذِهِ الْبُيُوتُ وَاسِعَةٌ/);
  assert.match(lessonSeventeen, /export const lessonSeventeen: Lesson/);
  assert.match(lessonSeventeen, /مَسَاجِدُ/);
  assert.match(lessonSeventeen, /هَلْ أَبُوكَ عَالِمٌ أَوَلَا؟/);
  assert.match(lessonEighteen, /export const lessonEighteen: Lesson/);
  assert.match(lessonEighteen, /مَحَابِرُ/);
  assert.match(lessonEighteen, /هَلْ لَكَ قَلَمٌ وَمِحْبَرَةٌ؟/);
  assert.match(lessonNineteen, /export const lessonNineteen: Lesson/);
  assert.match(lessonNineteen, /مُعْوَجٌّ/);
  assert.match(lessonNineteen, /عَصَايَ قَصِيرَةٌ/);
  assert.match(lessonTwenty, /export const lessonTwenty: Lesson/);
  assert.match(lessonTwenty, /بَيْضَاءُ/);
  assert.match(lessonTwenty, /هَذِهِ الْوَرَقَةُ خَضْرَاءُ/);
  assert.match(lessonTwentyOne, /export const lessonTwentyOne: Lesson/);
  assert.match(lessonTwentyOne, /مَدَحْتُنَّ/);
  assert.match(lessonTwentyOne, /مَدَحَ عَلِيٌّ أَبَاكَ/);
  assert.match(lessonTwentyTwo, /export const lessonTwentyTwo: Lesson/);
  assert.match(lessonTwentyTwo, /مِرَارًا/);
  assert.match(lessonTwentyTwo, /مَا سُرِقَ شَيْءٌ/);
  assert.match(lessonTwentyThree, /export const lessonTwentyThree: Lesson/);
  assert.match(lessonTwentyThree, /كَمِثْلِي/);
  assert.match(lessonTwentyThree, /رَجَعَ مِنِّي/);
  assert.match(lessonTwentyFour, /export const lessonTwentyFour: Lesson/);
  assert.match(lessonTwentyFour, /صَلَاةُ الْعِشَاءِ/);
  assert.match(lessonTwentyFour, /مَا ضَرَبَ أَحَدًا/);
  assert.match(lessonTwentyFive, /export const lessonTwentyFive: Lesson/);
  assert.match(lessonTwentyFive, /يَوْمُ الْخَمِيسِ/);
  assert.match(lessonTwentyFive, /رَجَعَ عَلِيٌّ مِنَ السُّوقِ الْبَارِحَةَ/);
  assert.match(lessonTwentySix, /export const lessonTwentySix: Lesson/);
  assert.match(lessonTwentySix, /إِلَى مَتَى/);
  assert.match(lessonTwentySix, /جَلَسْتُ تَحْتَ الشَّجَرَةِ/);
  assert.match(lessonTwentySeven, /export const lessonTwentySeven: Lesson/);
  assert.match(lessonTwentySeven, /بَيْنَمَا/);
  assert.match(lessonTwentySeven, /ذُو الْحِجَّةِ/);
  assert.match(lessonTwentyEight, /export const lessonTwentyEight: Lesson/);
  assert.match(lessonTwentyEight, /أَشْرِبَةٌ/);
  assert.match(lessonTwentyEight, /لَعِبَ هَذَا الْوَلَدُ/);
  assert.match(lessonTwentyNine, /export const lessonTwentyNine: Lesson/);
  assert.match(lessonTwentyNine, /جَرَائِدُ/);
  assert.match(lessonTwentyNine, /عَمَلِي عَسِيرٌ/);
  assert.match(lessonThirty, /export const lessonThirty: Lesson/);
  assert.match(lessonThirty, /اللَّاتِي/);
  assert.match(lessonThirty, /حَمَلْتُ هَذَا الصُّنْدُوقَ وَحْدِي/);
  assert.match(lessonThirtyOne, /export const lessonThirtyOne: Lesson/);
  assert.match(lessonThirtyOne, /سَوْفَ يَمْدَحُ/);
  assert.match(lessonThirtyOne, /لَا نُمْدَحُ/);
  assert.match(lessonThirtyTwo, /export const lessonThirtyTwo: Lesson/);
  assert.match(lessonThirtyTwo, /يَحْفَظُ/);
  assert.match(lessonThirtyTwo, /الصُّلَحَاءُ لَا يَتْرُكُونَ الصَّلَاةَ/);
  assert.match(lessonThirtyThree, /export const lessonThirtyThree: Lesson/);
  assert.match(lessonThirtyThree, /اِمْدَحُوا/);
  assert.match(lessonThirtyThree, /أَوَّلًا اِفْهَمْ ثُمَّ اِفْعَلْ/);
  assert.match(lessonThirtyFour, /export const lessonThirtyFour: Lesson/);
  assert.match(lessonThirtyFour, /يَا أَيَّتُهَا النِّسَاءُ/);
  assert.match(lessonThirtyFour, /اِطْرَحِ الْحَجَرَ وَلَا تَطْرَحِ الْكِتَابَ/);
  assert.match(lessonThirtyFive, /export const lessonThirtyFive: Lesson/);
  assert.match(lessonThirtyFive, /عَلَّامُ الْغُيُوبِ/);
  assert.match(lessonThirtyFive, /الْمَسْأَلَةُ الْمَسْؤُولُ عَنْهَا/);
  assert.match(lessonThirtySix, /export const lessonThirtySix: Lesson/);
  assert.match(lessonThirtySix, /غَيْرَ نَاظِرِينَ إِلَيْهِ/);
  assert.match(lessonThirtySix, /الدَّكَاكِينُ لَيْسَتْ بِمَفْتُوحَةٍ/);
  assert.match(lessonThirtySeven, /export const lessonThirtySeven: Lesson/);
  assert.match(lessonThirtySeven, /أَرْحَمُ الرَّاحِمِينَ/);
  assert.match(lessonThirtySeven, /قَلَمِي أَطْوَلُ مِنْ قَلَمِكَ/);
  assert.match(lessonThirtyEight, /export const lessonThirtyEight: Lesson/);
  assert.match(lessonThirtyEight, /سَبَبُ الْعِلْمِ الْقِرَاءَةُ/);
  assert.match(lessonThirtyEight, /وَظَائِفُ الْخُدَّامِ كَثِيرَةٌ/);
  assert.match(lessonThirtyNine, /export const lessonThirtyNine: Lesson/);
  assert.match(lessonThirtyNine, /السَّخَاوَةُ فَضِيلَةٌ/);
  assert.match(lessonThirtyNine, /الصَّبْرُ خَيْرٌ مِنَ الْعَجَلَةِ/);
  assert.match(lessonForty, /export const lessonForty: Lesson/);
  assert.match(lessonForty, /الصِّحَّةُ نِعْمَةٌ وَالْمَرَضُ آفَةٌ/);
  assert.match(lessonForty, /جَوَازُ هَذَا الْفِعْلِ مَعْلُومٌ لَنَا/);
  assert.match(lessonFortyOne, /export const lessonFortyOne: Lesson/);
  assert.match(lessonFortyOne, /الْجَمَدُ مَاءٌ جَامِدٌ/);
  assert.match(lessonFortyOne, /الْمَاءُ يَلْمَعُ لَمَعَانًا عَجِيبًا/);
  assert.match(lessonFortyTwo, /export const lessonFortyTwo: Lesson/);
  assert.match(lessonFortyTwo, /حَوْلَ قَرْيَتِنَا جِبَالٌ وَأَوْدِيَةٌ/);
  assert.match(lessonFortyTwo, /مَاءُ النَّهْرِ جَارٍ/);
  assert.match(lessonFortyThree, /export const lessonFortyThree: Lesson/);
  assert.match(lessonFortyThree, /أَكْمَامُ الْقَمِيصِ طَوِيلَةٌ/);
  assert.match(lessonFortyThree, /صَبَغَ الصَّبَّاغُ/);
  assert.match(lessonFortyFour, /export const lessonFortyFour: Lesson/);
  assert.match(lessonFortyFour, /رَقَعَ الْخَيَّاطُ خُرُوقَ الثَّوْبِ/);
  assert.match(lessonFortyFour, /هَذِهِ الْمَنَادِيلُ رَطْبَةٌ/);
  assert.match(lessonFortyFive, /export const lessonFortyFive: Lesson/);
  assert.match(lessonFortyFive, /إِيمَانُ الْمُؤْمِنِينَ بِاللَّهِ قَوِيٌّ/);
  assert.match(lessonFortySix, /export const lessonFortySix: Lesson/);
  assert.match(lessonFortySeven, /export const lessonFortySeven: Lesson/);
  assert.match(lessonFortySeven, /الصَّبْرُ خَيْرٌ مِنَ الْعَجَلَةِ/);
  assert.match(lessonFortyEight, /export const lessonFortyEight: Lesson/);
  assert.match(lessonFortyNine, /export const lessonFortyNine: Lesson/);
  assert.match(lessonFifty, /طَلَبُ الْعِلْمِ فَرِيضَةٌ/);
  assert.match(lessonFiftyOne, /لِلْإِنْسَانِ عَيْنَانِ وَأُذُنَانِ/);
  assert.match(lessonFiftyTwo, /اغْسِلُوا أَيْدِيَكُمْ إِلَى الْمَرَافِقِ/);
  assert.match(lessonFiftyThree, /الدَّمُ يَجْرِي فِي الْعُرُوقِ/);
  assert.match(lessonFiftyFour, /لِلْحَيَوَانَاتِ فَوَائِدُ كَثِيرَةٌ/);
  assert.match(lessonFiftyFive, /الذِّئْبُ يُشْبِهُ الْكَلْبَ/);
  assert.match(lessonFiftySix, /يَجْمَعُ النَّحْلُ الْعَسَلَ مِنَ الْأَزْهَارِ/);
  assert.match(lessonFiftySeven, /لِلشَّجَرَةِ جُذُورٌ وَأَغْصَانٌ/);
  assert.match(lessonFiftyEight, /زَرَعَ الْفَلَّاحُ الْبُذُورَ فِي الْحَقْلِ/);
  assert.match(lessonFiftyNine, /الْبَيْتُ مَفْرُوشٌ بِالطَّنَافِسِ/);
  assert.match(lessonSixty, /تَشْرُقُ الشَّمْسُ مِنَ الْمَشْرِقِ/);
  assert.match(lessonSixtyOne, /الزُّجَاجَةُ شَفَّافَةٌ/);
  assert.match(lessonSixtyTwo, /السِّكَّةُ الْحَدِيدِيَّةُ/);
  assert.match(lessonSixtyThree, /مَزَجَ، يَمْزُجُ، الْمَزْجُ/);
  assert.match(lessonSixtyFour, /ثَلَاثَةُ رِجَالٍ/);
  assert.match(lessonSixtyFive, /كَمْ كِتَابًا قَرَأْتَ/);
  assert.match(lessonSixtySix, /أَلْفُ أَلْفٍ/);
  assert.match(lessonSixtySeven, /ثَلَاثُ مِائَةٍ وَخَمْسَةٌ وَسِتُّونَ يَوْمًا/);
  assert.match(lessonSixtyEight, /اِثْنَانِ \/ اِثْنَيْنِ/);
  assert.match(lessonSixtyNine, /لَا تَشْرَبَا أَنْتُمَا/);
  assert.match(lessonSeventy, /إِنَّ زَيْدًا عَالِمٌ/);
  assert.match(lessonSeventyOne, /الْمَدَارِسُ الْإِسْلَامِيَّةُ/);
  assert.match(lessonSeventyTwo, /مَجْمَعُ الْمِيَاهِ/);
  assert.match(lessonSeventyThree, /زَرَعَ — مَزْرَعَةٌ/);
  assert.match(lessonSeventyFour, /لَنْ يَفْتَحَ/);
  assert.match(lessonSeventyFive, /إِذَا عَطِشْتُمْ فَاشْرَبُوا/);
  assert.match(lessonSeventySix, /إِكْرَامٌ/);
  assert.match(lessonSeventySeven, /الْمُؤْمِنُونَ يَتَنَاصَرُونَ/);
  assert.match(lessonSeventyEight, /اِجْتَنِبُوا الذُّنُوبَ وَالْعُيُوبَ/);
  assert.match(lessonSeventyNine, /مَرَّ — يَمُرُّ/);
  assert.match(lessonEighty, /وَعَدَ، يَعِدُ، الْوَعْدُ/);
  assert.match(lessonFortyEight, /لَمْ يَقْرَأْ وَلَمْ يَكْتُبْ/);
  assert.match(lessonFortySix, /الدُّنْيَا فَانِيَةٌ وَالْآخِرَةُ بَاقِيَةٌ/);
  assert.match(page, /import \{ rawLessons, type Lesson, type Question \} from "\.\.\/content"/);
  assert.match(page, /shifahiya-active-session/);
  assert.match(page, /shifahiya-session-\$\{lessonId\}/);
  assert.match(page, /unfinished \? "Продолжить"/);
  assert.match(page, /restoreSession\(storedSession\)/);
  assert.match(page, /shifahiya-card-progress-v1/);
  assert.match(page, /REVIEW_INTERVALS = \[0, 1, 3, 7, 14, 30\]/);
  assert.match(page, /Повторить сейчас/);
  assert.match(page, /rateLearningCard\(false\)/);
  assert.match(page, /rateReviewCard\(true\)/);
  assert.match(page, /Сохранить копию/);
  assert.match(page, /shifahiya-learning-stats-v1/);
  assert.match(page, /WORD_ACHIEVEMENTS = \[10, 50, 100, 250, 500, 1000, 1500, 2000\]/);
  assert.match(page, /Ваш путь в цифрах/);
  assert.match(page, /слов выучено/);
  assert.match(page, /рекорд без перерыва/);
  assert.match(page, /Продолжить обучение/);
  assert.match(page, /latestSessionPosition/);
  assert.match(page, /Следующий шаг/);
  assert.match(page, /recommendedLesson/);
  assert.match(page, /updatedAt: Date\.now\(\)/);
  assert.doesNotMatch(page, /setSavedSessions\(\{ \.\.\.sessions \}\);\s+restoreSession\(session\)/);
  assert.match(page, /shifahiya-lesson-\$\{item\.id\}/);
  assert.match(page, /shuffle\(currentQuestion\?\.options/);
  assert.match(page, /const targetCount = words\.length \* 2/);
  assert.match(page, /\.map\(expandLessonQuestions\)/);
});
