// Generated by scripts/import-reading.mjs — do not edit by hand.
import type { ReadingSummary } from "./types";

export const READING_SOURCE = "Мабдауль кыраат. Часть 1";

/** Which lesson carries which text, and how long the text is. */
export const readingSummaries: ReadingSummary[] = [
  { id: 1, lessonId: 36, textCount: 2, sentenceCount: 29 },
  { id: 2, lessonId: 40, textCount: 2, sentenceCount: 38 },
  { id: 3, lessonId: 41, textCount: 2, sentenceCount: 38 },
  { id: 4, lessonId: 42, textCount: 2, sentenceCount: 42 },
  { id: 5, lessonId: 52, textCount: 2, sentenceCount: 48 },
  { id: 6, lessonId: 65, textCount: 2, sentenceCount: 43 },
  { id: 7, lessonId: 66, textCount: 2, sentenceCount: 37 },
  { id: 8, lessonId: 67, textCount: 2, sentenceCount: 44 },
  { id: 9, lessonId: 69, textCount: 2, sentenceCount: 40 },
  { id: 10, lessonId: 73, textCount: 2, sentenceCount: 38 },
  { id: 11, lessonId: 75, textCount: 2, sentenceCount: 28 },
  { id: 12, lessonId: 77, textCount: 2, sentenceCount: 18 },
  { id: 13, lessonId: 78, textCount: 2, sentenceCount: 28 },
  { id: 14, lessonId: 81, textCount: 2, sentenceCount: 38 },
  { id: 15, lessonId: 82, textCount: 2, sentenceCount: 35 },
  { id: 16, lessonId: 83, textCount: 2, sentenceCount: 34 },
  { id: 17, lessonId: 84, textCount: 2, sentenceCount: 31 },
  { id: 18, lessonId: 86, textCount: 2, sentenceCount: 30 },
  { id: 19, lessonId: 87, textCount: 2, sentenceCount: 38 },
  { id: 20, lessonId: 88, textCount: 2, sentenceCount: 36 },
  { id: 21, lessonId: 90, textCount: 2, sentenceCount: 44 },
  { id: 22, lessonId: 91, textCount: 2, sentenceCount: 23 },
  { id: 23, lessonId: 92, textCount: 2, sentenceCount: 29 },
  { id: 24, lessonId: 95, textCount: 2, sentenceCount: 16 },
  { id: 25, lessonId: 96, textCount: 2, sentenceCount: 25 },
];

export const readingByLesson = new Map(readingSummaries.map((item) => [item.lessonId, item]));
