// Generated by scripts/import-podcasts.mjs — do not edit by hand.
// Run `npm run podcasts:import` with a YOUTUBE_API_KEY to refresh it.
//
// The episode list ships with the site so that the app works the moment it is
// opened, with no key and no network call of its own. It is a snapshot: new
// episodes appear here when the importer is run again, and until then the app
// offers what was known at build time. A learner who wants the list to refresh
// itself can put their own API key into the app's settings, and the device then
// keeps its own newer copy.
import type { PodcastCatalog } from "../../app/podcast-catalog.ts";

export const shippedCatalog: PodcastCatalog = {
  generatedAt: "",
  channels: [],
  videos: [],
};
