// Turns a Frank-method parallel text (the JSON the translator exports: a flat
// list of ar/ru sentence pairs grouped by lesson) into the reading sections the
// course serves, one file per section.
//
//   node scripts/import-reading.mjs <path-to.json>
//
// The host lesson for each section is chosen here rather than by hand: the
// texts go to the lightest lessons of the stretch, so that a learner meets them
// where the lesson itself asks least of them.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const { lessonSummaries } = await import("../content/manifest.ts");

const FIRST_LESSON = 35;
const LAST_LESSON = 96;
const NUMBERS = [
  "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten",
  "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen",
  "Eighteen", "Nineteen", "Twenty", "TwentyOne", "TwentyTwo", "TwentyThree",
  "TwentyFour", "TwentyFive",
];

/**
 * Lessons that can take a text: inside the stretch, not split into parts, and
 * without a grammar block — both of those already give the lesson a second
 * part. Of those, the ones with the fewest exercises, spread over the range.
 */
export function hostLessons(count) {
  const free = lessonSummaries.filter(
    (item) =>
      item.id >= FIRST_LESSON &&
      item.id <= LAST_LESSON &&
      item.partCount === 1 &&
      item.grammarQuestionCount === 0,
  );
  return free
    .slice()
    .sort((a, b) => a.questionCount - b.questionCount || a.id - b.id)
    .slice(0, count)
    .map((item) => item.id)
    .sort((a, b) => a - b);
}

/**
 * Pairs the source cannot answer for. s9-027 (مِخْرَةٌ كَبِيرٌ) carries the gloss
 * "Necrosis majus" where the Russian should be — a slip somewhere upstream, and
 * not a word to guess at in teaching material. The line is left out until the
 * translator says what it means.
 */
const SKIPPED = new Set(["s9-027"]);

function sectionsOf(payload) {
  const sections = new Map();
  for (const item of payload.items) {
    if (SKIPPED.has(item.id)) continue;
    const section = sections.get(item.lesson) ?? { id: item.lesson, texts: [] };
    sections.set(item.lesson, section);
    if (item.type === "title") {
      section.texts.push({ title: item.ru.trim(), sentences: [] });
      continue;
    }
    // A pair before any title still belongs somewhere: give it a text of its own.
    if (!section.texts.length) section.texts.push({ title: `Текст ${section.texts.length + 1}`, sentences: [] });
    section.texts.at(-1).sentences.push({ arabic: item.ar.trim(), russian: item.ru.trim() });
  }
  return [...sections.values()]
    .sort((a, b) => a.id - b.id)
    .map((section, index) => ({ ...section, id: index + 1, texts: section.texts.filter((text) => text.sentences.length) }));
}

function render(section, lessonId, source) {
  const texts = section.texts
    .map((text) => {
      const sentences = text.sentences
        .map((line) => `        { arabic: ${JSON.stringify(line.arabic)}, russian: ${JSON.stringify(line.russian)} },`)
        .join("\n");
      return `    {\n      title: ${JSON.stringify(text.title)},\n      sentences: [\n${sentences}\n      ],\n    },`;
    })
    .join("\n");

  return `import type { ReadingSection } from "../types";

export const reading${NUMBERS[section.id - 1]}: ReadingSection = {
  id: ${section.id},
  lessonId: ${lessonId},
  source: ${JSON.stringify(source)},
  texts: [
${texts}
  ],
};
`;
}

const source = process.argv[2];
if (!source) {
  console.error("usage: node scripts/import-reading.mjs <path-to.json>");
  process.exit(1);
}

const payload = JSON.parse(await readFile(source, "utf8"));
const sections = sectionsOf(payload);
const hosts = hostLessons(sections.length);
if (hosts.length < sections.length) {
  console.error(`only ${hosts.length} lessons are free, need ${sections.length}`);
  process.exit(1);
}

const directory = fileURLToPath(new URL("../content/reading/", import.meta.url));
await mkdir(directory, { recursive: true });

for (const [index, section] of sections.entries()) {
  const name = `section-${String(section.id).padStart(2, "0")}.ts`;
  await writeFile(directory + name, render(section, hosts[index], payload.title), "utf8");
}

const summaries = sections
  .map((section, index) => {
    const sentences = section.texts.reduce((total, text) => total + text.sentences.length, 0);
    return `  { id: ${section.id}, lessonId: ${hosts[index]}, textCount: ${section.texts.length}, sentenceCount: ${sentences} },`;
  })
  .join("\n");

await writeFile(
  fileURLToPath(new URL("../content/reading-manifest.ts", import.meta.url)),
  `// Generated by scripts/import-reading.mjs — do not edit by hand.
import type { ReadingSummary } from "./types";

export const READING_SOURCE = ${JSON.stringify(payload.title)};

/** Which lesson carries which text, and how long the text is. */
export const readingSummaries: ReadingSummary[] = [
${summaries}
];

export const readingByLesson = new Map(readingSummaries.map((item) => [item.lessonId, item]));
`,
  "utf8",
);

const total = sections.reduce((sum, section) => sum + section.texts.reduce((count, text) => count + text.sentences.length, 0), 0);
console.log(`${sections.length} sections, ${total} sentences → lessons ${hosts.join(", ")}`);
